"""fourth migration

Revision ID: 1d3e844ebb0b
Revises: ab7be78b9c60
Create Date: 2021-06-23 15:36:28.837018

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '1d3e844ebb0b'
down_revision = 'ab7be78b9c60'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('admin', sa.Column('problem_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'admin', 'comments', ['problem_id'], ['id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'admin', type_='foreignkey')
    op.drop_column('admin', 'problem_id')
    # ### end Alembic commands ###
