"""migrate

Revision ID: 4928a252b617
Revises: bb276ed9646f
Create Date: 2021-06-23 05:56:21.514184

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '4928a252b617'
down_revision = 'bb276ed9646f'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('problem', sa.Column('category', sa.String(length=255), nullable=True))
    op.drop_column('problem', 'Category')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('problem', sa.Column('Category', sa.VARCHAR(length=255), autoincrement=False, nullable=True))
    op.drop_column('problem', 'category')
    # ### end Alembic commands ###
