"""add department colulumn

Revision ID: 88b335f88648
Revises: b6fe63049c1b
Create Date: 2021-06-23 15:41:06.359463

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '88b335f88648'
down_revision = 'b6fe63049c1b'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('comments', sa.Column('departments', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('comments', 'departments')
    # ### end Alembic commands ###
