"""Initial Migration

Revision ID: 88df635d7564
Revises: c5ed8a33bbec
Create Date: 2021-06-23 12:00:12.293763

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '88df635d7564'
down_revision = 'c5ed8a33bbec'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('role', sa.String(length=64), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'role')
    # ### end Alembic commands ###
