"""add department colulumn

Revision ID: b48531341e6c
Revises: 88b335f88648
Create Date: 2021-06-23 15:46:14.622608

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'b48531341e6c'
down_revision = '88b335f88648'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('comments', sa.Column('department', sa.String(), nullable=True))
    op.drop_column('comments', 'departments')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('comments', sa.Column('departments', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.drop_column('comments', 'department')
    # ### end Alembic commands ###
