"""fifth migration

Revision ID: d43ab375893a
Revises: 1d3e844ebb0b
Create Date: 2021-06-23 15:41:57.184346

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'd43ab375893a'
down_revision = '1d3e844ebb0b'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('admin', sa.Column('comment_id', sa.Integer(), nullable=True))
    op.drop_constraint('admin_problem_id_fkey', 'admin', type_='foreignkey')
    op.create_foreign_key(None, 'admin', 'comments', ['comment_id'], ['id'])
    op.create_foreign_key(None, 'admin', 'problem', ['problem_id'], ['id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'admin', type_='foreignkey')
    op.drop_constraint(None, 'admin', type_='foreignkey')
    op.create_foreign_key('admin_problem_id_fkey', 'admin', 'comments', ['problem_id'], ['id'])
    op.drop_column('admin', 'comment_id')
    # ### end Alembic commands ###
